CHARACTERS = [
    {
        "slug": "monkey-d-luffy",
        "name": "Monkey D. Luffy",
        "epithet": "Chapéu de Palha",
        "crew": "Piratas do Chapéu de Palha",
        "role": "Capitão",
        "bounty": 3_000_000_000,
        "origin": "East Blue",
        "symbol": "☀️",
        "description": "Um pirata movido pelo sonho de encontrar o grande tesouro e se tornar o Rei dos Piratas.",
    },
    {
        "slug": "roronoa-zoro",
        "name": "Roronoa Zoro",
        "epithet": "Caçador de Piratas",
        "crew": "Piratas do Chapéu de Palha",
        "role": "Espadachim",
        "bounty": 1_111_000_000,
        "origin": "East Blue",
        "symbol": "⚔️",
        "description": "Espadachim de três lâminas que pretende superar todos os adversários e se tornar o melhor do mundo.",
    },
    {
        "slug": "sanji",
        "name": "Sanji",
        "epithet": "Perna Negra",
        "crew": "Piratas do Chapéu de Palha",
        "role": "Cozinheiro",
        "bounty": 1_032_000_000,
        "origin": "North Blue",
        "symbol": "🔥",
        "description": "Cozinheiro e lutador que procura o All Blue, o lendário mar onde peixes de todos os oceanos se encontram.",
    },
    {
        "slug": "nico-robin",
        "name": "Nico Robin",
        "epithet": "Criança Demônio",
        "crew": "Piratas do Chapéu de Palha",
        "role": "Arqueóloga",
        "bounty": 930_000_000,
        "origin": "West Blue",
        "symbol": "📜",
        "description": "Arqueóloga capaz de ler os Poneglyphs e determinada a descobrir a verdadeira história do mundo.",
    },
    {
        "slug": "brook",
        "name": "Brook",
        "epithet": "Soul King",
        "crew": "Piratas do Chapéu de Palha",
        "role": "Músico",
        "bounty": 383_000_000,
        "origin": "West Blue",
        "symbol": "🎻",
        "description": "Músico esqueleto que deseja reencontrar Laboon depois de cumprir a promessa feita por sua antiga tripulação.",
    },
    {
        "slug": "trafalgar-law",
        "name": "Trafalgar D. Water Law",
        "epithet": "Cirurgião da Morte",
        "crew": "Piratas Heart",
        "role": "Capitão e médico",
        "bounty": 3_000_000_000,
        "origin": "North Blue",
        "symbol": "🫀",
        "description": "Capitão estrategista e médico que usa os poderes da Ope Ope no Mi para controlar seu campo de operação.",
    },
    {
        "slug": "shanks",
        "name": "Shanks",
        "epithet": "Ruivo",
        "crew": "Piratas do Ruivo",
        "role": "Capitão",
        "bounty": 4_048_900_000,
        "origin": "West Blue",
        "symbol": "🗡️",
        "description": "Um dos piratas mais influentes dos mares e a figura que inspirou Luffy a iniciar sua jornada.",
    },
    {
        "slug": "marshall-d-teach",
        "name": "Marshall D. Teach",
        "epithet": "Barba Negra",
        "crew": "Piratas do Barba Negra",
        "role": "Capitão",
        "bounty": 3_996_000_000,
        "origin": "Grand Line",
        "symbol": "🌑",
        "description": "Pirata ambicioso que avançou rapidamente pelo Novo Mundo acumulando poder e uma tripulação perigosa.",
    },
]
